/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'status' : ApplicationStatus,
  'player' : Player,
  'reviewer' : [] | [Principal],
}
export interface ApplicationEntry {
  'principal' : Principal,
  'submitterTags' : Array<PlayerTag>,
  'application' : Application,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Gamemode = { 'all' : null } |
  { 'uhc' : null } |
  { 'smpPvp' : null } |
  { 'axePvp' : null } |
  { 'swordPvp' : null } |
  { 'nethpot' : null } |
  { 'crystalPvp' : null } |
  { 'macePvp' : null } |
  { 'cartPvp' : null };
export interface Player {
  'smpPvpTier' : Tier,
  'username' : string,
  'axePvpTier' : Tier,
  'crystalPvpTier' : Tier,
  'cartPvpTier' : Tier,
  'overallTier' : Tier,
  'nethpotTier' : Tier,
  'discord' : [] | [string],
  'macePvpTier' : Tier,
  'uhcTier' : Tier,
  'swordPvpTier' : Tier,
}
export type PlayerTag = { 'new' : null } |
  { 'player' : null } |
  { 'experienced' : null } |
  { 'tierTester' : null };
export type Principal = Principal;
export interface ProfileEntry {
  'principal' : Principal,
  'name' : string,
  'tags' : Array<PlayerTag>,
}
export type Tier = { 'ht1' : null } |
  { 'ht2' : null } |
  { 'ht3' : null } |
  { 'ht4' : null } |
  { 'ht5' : null } |
  { 'lt1' : null } |
  { 'lt2' : null } |
  { 'lt3' : null } |
  { 'lt4' : null } |
  { 'lt5' : null } |
  { 'mt1' : null } |
  { 'mt2' : null } |
  { 'mt3' : null } |
  { 'mt4' : null } |
  { 'mt5' : null } |
  { 'none' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminCreatePendingApplication' : ActorMethod<[Principal], undefined>,
  'adminUpdatePendingRanks' : ActorMethod<[Principal, Player], undefined>,
  'claimAdminRoleWithPassword' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPlayerTags' : ActorMethod<[Principal, Array<PlayerTag>], undefined>,
  'assignTesterRole' : ActorMethod<[Principal], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'deletePlayer' : ActorMethod<[Principal], undefined>,
  'editPlayer' : ActorMethod<[Principal, Player], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<ProfileEntry>>,
  'getApplication' : ActorMethod<[Principal], Application>,
  'getBannedUsers' : ActorMethod<[], Array<Principal>>,
  'getByGamemode' : ActorMethod<[Gamemode], Array<Player>>,
  'getByTier' : ActorMethod<[Tier], Array<Player>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<Player>>,
  'getOwnedApplications' : ActorMethod<[], Array<Application>>,
  'getPlayerByUsername' : ActorMethod<[string], Player>,
  'getPlayerTags' : ActorMethod<[Principal], Array<PlayerTag>>,
  'getProfileEntry' : ActorMethod<[Principal], [] | [ProfileEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllApplicationsWithPrincipals' : ActorMethod<
    [],
    Array<ApplicationEntry>
  >,
  'listAllApprovedPlayers' : ActorMethod<[], Array<Player>>,
  'listAllPendingApplications' : ActorMethod<[], Array<Application>>,
  'listAllUsernames' : ActorMethod<[], Array<string>>,
  'reviewApplication' : ActorMethod<[Principal, boolean], undefined>,
  'revokeTesterRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitApplication' : ActorMethod<
    [
      string,
      [] | [string],
      Tier,
      Tier,
      Tier,
      Tier,
      Tier,
      Tier,
      Tier,
      Tier,
      Tier,
    ],
    undefined
  >,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'testerSubmitForOtherPlayer' : ActorMethod<[Principal, Player], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
