/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Principal = IDL.Principal;
export const Tier = IDL.Variant({
  'ht1' : IDL.Null,
  'ht2' : IDL.Null,
  'ht3' : IDL.Null,
  'ht4' : IDL.Null,
  'ht5' : IDL.Null,
  'lt1' : IDL.Null,
  'lt2' : IDL.Null,
  'lt3' : IDL.Null,
  'lt4' : IDL.Null,
  'lt5' : IDL.Null,
  'mt1' : IDL.Null,
  'mt2' : IDL.Null,
  'mt3' : IDL.Null,
  'mt4' : IDL.Null,
  'mt5' : IDL.Null,
  'none' : IDL.Null,
});
export const Player = IDL.Record({
  'smpPvpTier' : Tier,
  'username' : IDL.Text,
  'axePvpTier' : Tier,
  'crystalPvpTier' : Tier,
  'cartPvpTier' : Tier,
  'overallTier' : Tier,
  'nethpotTier' : Tier,
  'discord' : IDL.Opt(IDL.Text),
  'macePvpTier' : Tier,
  'uhcTier' : Tier,
  'swordPvpTier' : Tier,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Application = IDL.Record({
  'status' : ApplicationStatus,
  'player' : Player,
  'reviewer' : IDL.Opt(Principal),
});
export const Gamemode = IDL.Variant({
  'all' : IDL.Null,
  'uhc' : IDL.Null,
  'smpPvp' : IDL.Null,
  'axePvp' : IDL.Null,
  'swordPvp' : IDL.Null,
  'nethpot' : IDL.Null,
  'crystalPvp' : IDL.Null,
  'macePvp' : IDL.Null,
  'cartPvp' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTesterRole' : IDL.Func([Principal], [], []),
  'deletePlayer' : IDL.Func([Principal], [], []),
  'editPlayer' : IDL.Func([Principal, Player], [], []),
  'getApplication' : IDL.Func([Principal], [Application], ['query']),
  'getByGamemode' : IDL.Func([Gamemode], [IDL.Vec(Player)], ['query']),
  'getByTier' : IDL.Func([Tier], [IDL.Vec(Player)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getOwnedApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getPlayerByUsername' : IDL.Func([IDL.Text], [Player], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllApprovedPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'listAllPendingApplications' : IDL.Func(
      [],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'listAllUsernames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'reviewApplication' : IDL.Func([Principal, IDL.Bool], [], []),
  'revokeTesterRole' : IDL.Func([Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        Tier,
        Tier,
        Tier,
        Tier,
        Tier,
        Tier,
        Tier,
        Tier,
        Tier,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const Tier = IDL.Variant({
    'ht1' : IDL.Null,
    'ht2' : IDL.Null,
    'ht3' : IDL.Null,
    'ht4' : IDL.Null,
    'ht5' : IDL.Null,
    'lt1' : IDL.Null,
    'lt2' : IDL.Null,
    'lt3' : IDL.Null,
    'lt4' : IDL.Null,
    'lt5' : IDL.Null,
    'mt1' : IDL.Null,
    'mt2' : IDL.Null,
    'mt3' : IDL.Null,
    'mt4' : IDL.Null,
    'mt5' : IDL.Null,
    'none' : IDL.Null,
  });
  const Player = IDL.Record({
    'smpPvpTier' : Tier,
    'username' : IDL.Text,
    'axePvpTier' : Tier,
    'crystalPvpTier' : Tier,
    'cartPvpTier' : Tier,
    'overallTier' : Tier,
    'nethpotTier' : Tier,
    'discord' : IDL.Opt(IDL.Text),
    'macePvpTier' : Tier,
    'uhcTier' : Tier,
    'swordPvpTier' : Tier,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Application = IDL.Record({
    'status' : ApplicationStatus,
    'player' : Player,
    'reviewer' : IDL.Opt(Principal),
  });
  const Gamemode = IDL.Variant({
    'all' : IDL.Null,
    'uhc' : IDL.Null,
    'smpPvp' : IDL.Null,
    'axePvp' : IDL.Null,
    'swordPvp' : IDL.Null,
    'nethpot' : IDL.Null,
    'crystalPvp' : IDL.Null,
    'macePvp' : IDL.Null,
    'cartPvp' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTesterRole' : IDL.Func([Principal], [], []),
    'deletePlayer' : IDL.Func([Principal], [], []),
    'editPlayer' : IDL.Func([Principal, Player], [], []),
    'getApplication' : IDL.Func([Principal], [Application], ['query']),
    'getByGamemode' : IDL.Func([Gamemode], [IDL.Vec(Player)], ['query']),
    'getByTier' : IDL.Func([Tier], [IDL.Vec(Player)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getOwnedApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getPlayerByUsername' : IDL.Func([IDL.Text], [Player], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllApprovedPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'listAllPendingApplications' : IDL.Func(
        [],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'listAllUsernames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'reviewApplication' : IDL.Func([Principal, IDL.Bool], [], []),
    'revokeTesterRole' : IDL.Func([Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          Tier,
          Tier,
          Tier,
          Tier,
          Tier,
          Tier,
          Tier,
          Tier,
          Tier,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };